  
on: 
 push:
  branches:
      - branch1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name Sebastian Peter
          git config user.email mail2sebastianpeter@gmail.com
          git checkout branch2
          git merge origin/banch1
          git push -u origin branch2
          gh --version
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          gh pr create --title "The bug is fixed" --body "Everything works again" --base main --head banch
